apiVersion: v1
kind: Service
metadata:
  labels:
    name: pttg-mongodb
  name: pttg-mongodb
spec:
  type: NodePort
  ports:
  - name: http
    port: 27017
    containerPort: http
    nodePort: ${ptincome_port}
  selector:
    name: pttg-mongodb
