apiVersion: v1
kind: ReplicationController
metadata:
  name: pttg-mongodb
  labels:
    name: pttg-mongodb
spec:
  replicas: 1
  selector:
    name: pttg-mongodb
  template:
    metadata:
      labels:
        name: pttg-mongodb
    spec:
      containers:
      - name: pttg-mongodb
        image: quay.io/ukhomeofficedigital/pttg-test-mongodb:${ pt-income-version }
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 1024Mi
        ports:
          - name: http
            containerPort: 27017
        imagePullPolicy: Always
