apiVersion: v1
kind: ReplicationController
metadata:
  name: pttg-mongodb
  labels:
    name: pttg-mongodb
spec:
  replicas: 1
  selector:
    name: pttg-mongodb
  template:
    metadata:
      labels:
        name: pttg-mongodb
    spec:
      containers:
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy:v1.1.5
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '27017'
          - name: LOAD_BALANCER_CIDR
            value: '10.50.0.0/22'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 443
      - name: pttg-mongodb
        image: quay.io/ukhomeofficedigital/pttg-mongodb:${ pt-income-version }
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 1024Mi
        ports:
          - name: http
            containerPort: 27017
        imagePullPolicy: Always
